name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use java ${{ matrix.java-version }}
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'

      - run: mvn versions:use-latest-releases -Dtest=BasicDemo -Dci_test=true test
        env:
          APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}

      - uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          BRANCH_NAME: 'master'